### ISSUE TITLE
error: could not determine host

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-go#109]
The following GoLog error message is cropping up when starting up on android (sim):

```
E/GoLog: [0;37m20:22:15.880 [31mERROR [0;34m core: [0mmdns error: could not determine host: open /proc/sys/kernel/hostname: permission denied [0;37mbuilder.go:219 [0m
```

Seems to be referring to P2P host, but shared etc _are_ coming through.

**Comment by sanderpick** [comment]
closing this for now, doesn't seem to be a problem
