### ISSUE TITLE
Republishing question

### ISSUE THREAD

**Issue by drwasho** [textileio/textile-go#137]
I think the default time before pointers expire from the IPFS DHT is about 3 days, unless the node republishes. How are you handling that, because for us at OpenBazaar we found it was too short and created a fork of the network to allow longer periods of time before republishing?

**Comment by sanderpick** [comment]
@drwasho I think I misunderstood your question - you're asking about these [pointers](https://github.com/OpenBazaar/openbazaar-go/blob/master/ipfs/pointers.go), right? I didn't adopt that piece of OB in Textile originally, although now am looking to as we move away from the pubsub hack I mentioned above.
