### ISSUE TITLE
Empty photo block items set returned as null

### ISSUE THREAD

**Issue by asutula** [textileio/textile-go#150]
Might be an easier to use api if it returned `[]`. Experiencing this behavior calling `getPhotoBlocks` from the mobile native layer.

**Comment by sanderpick** [comment]
Hmm, that doens't sound right... the core api returns `[]repo.Block`, the mobile wrapper converts that to json with an object wrapper:
```
type Blocks struct {
	Items []repo.Block `json:"items"`
}
```
Could possibly be an issue in the bridges, or just a bug. Can try and take a look today... but PRs are welcome or course... no departmental lines here :)

**Comment by asutula** [comment]
Yea, and it's not just as simple as making sure the Go code works as expected... We're generating the Android and iOS apis using `gobind`, so it's also a matter of understanding how that works.

**Comment by sanderpick** [comment]
totally
