### ISSUE TITLE
getBlockData throws exception when data isn't found locally

### ISSUE THREAD

**Issue by asutula** [textileio/textile-go#151]
I sometimes see the error coming from the go layer: `block not found locally`.

I think this error happens when they data you're querying for doesn't exist for a valid reason (like the user didn't comment on their photo). Need to do some more testing to totally understand the behavior, but let's decide what we think the correct behavior is... Return `null`? Something else?

**Comment by asutula** [comment]
Throwing and exception seems appropriate when we think there should be data, but there isn't or something goes wrong.

**Comment by asutula** [comment]
Yea this is actually causing images to never display on Android. Every time it does a query for photo hashes (and therefore data blocks for each photos caption), the caption query throws an exception and fails the photo refresh. (obviously the querying could be refactored to handle this case, but yea)

**Comment by asutula** [comment]
FYI... kinda documenting what I'm seeing as I dig into getting Android working with the latest Go layer. DISCLAIMER: I could definitely be jumping to conclusions, will provide more information as I find it.

**Comment by sanderpick** [comment]
definitely sounds like an error... the data would still exist even if they didn't caption it (just en empty string)
