### ISSUE TITLE
Needed node APIs for thread management

### ISSUE THREAD

**Issue by asutula** [textileio/textile-go#152]
Starting down the path of implementing thread creation and management. Looks like we need some additional APIs:
- [x] Join existing thread (will the existing `addThread` just work for this? YES)
- [x] List all threads I participate in
- [x] Thread metadata (members, invite link, etc)
- [x] Leave thread

**Comment by asutula** [comment]
Thread metadata could just come back as part of the list all threads API

**Comment by sanderpick** [comment]
list threads will need:
- thread id, name, public key, num peers

**Comment by sanderpick** [comment]
notes from related call:
- somehow include usernames in thread metadata
- how to include the "active" users in a thread?
- how to invite user to a thread that's not yet in the system?
