### ISSUE TITLE
addDevice method needs to return data

### ISSUE THREAD

**Issue by asutula** [textileio/textile-go#160]
At least the device id, maybe something like a `DeviceItem` representation of some sort

**Comment by sanderpick** [comment]
We could, but not sure it matters? The return data would be the same as what you put in...

```
AddDevice("desktop", "mydesktoppubkey")
```

The device id will be "mydesktoppubkey". It's like a `PUT` in a pure REST HTTP API.

**Comment by sanderpick** [comment]
Regardless, happy to return a `DeviceItem`. Just want to make sure you see the mechanism and still want it for convenience / consistency sake.

**Comment by asutula** [comment]
Oh right, we talked about this. The pubKey is the id. Ok, closing.
