### ISSUE TITLE
Thread related mobile APIs are thread name based

### ISSUE THREAD

**Issue by asutula** [textileio/textile-go#161]
This makes the assumption that thread names are unique. I don't think we can assume that once we launch shared threads. These APIs should be thread id based.

**Comment by asutula** [comment]
Also makes me think we should add an `isDefaultThread` to the `Thread` or `ThreadItem` object so we can identify which thread is the default one.

**Comment by asutula** [comment]
Hmm, actually no. A 'default' thread is a concept of the mobile app, we should put that state there, not in the Go layer. But that leaves the question, what if you delete the app, then re-install and recover your textile wallet in the future? How would we know which thread is the default thread?

**Comment by asutula** [comment]
Maybe we need the option for the client (the app) to specify the thread id when creating the thread. This messes up the use of public keys as thread id, but re purposing the public key like that is a fragile idea because of use cases like this.

**Comment by sanderpick** [comment]
pasting from slack for posterity:

Might be easier to chat about this but you can create a thread with a mnemonic or private key, but not public
That would cause issues
Also there’s a unique index on name
But doest have to match between peers
It’s sorta cosmetic - not important part of a thread
Was thinking that if you have to recover, you just get some generic naming like thread1 thread2 etc
Then some ui to rename your stuff

**Comment by asutula** [comment]
So if I'm invited to a thread that has the same name as a thread that already exists on my phone, I'll have to rename one of them?
