### ISSUE TITLE
Threads.Items is null when no threads exist

### ISSUE THREAD

**Issue by asutula** [textileio/textile-go#162]
Would be better if it were an empty array

**Comment by asutula** [comment]
This is seems when calling mobile.go `Threads()`

**Comment by sanderpick** [comment]
ah, good catch... empty and not-initialized in go are interchangeable, but the latter json-ifyes to null... changing

**Comment by asutula** [comment]
Cool, saw that commit fixes it for `Threads` and `Device`s. Don't forget about `Blocks` and `PinRequests`.
