### ISSUE TITLE
Missing Threads().Items

### ISSUE THREAD

**Issue by asutula** [textileio/textile-go#163]
Using the latest master of `textile-go` (just after merging #159 ), I'm seeing a strange behavior:

1. Fresh install (simulator)
2. App launches
3. App queries for threads, gets `{items: null}`
4. App successfully creates `default` and `null` threads.
5. After onboarding, threads are queried for again, gets an array of `ThreadItem` no problem

In every subsequent run of the app:

1. It launches, queries for existing threads, gets `{items: null}`
2. Tries to create `default` thread (because the `default` thread isn't listed in the threads query)
3. Gets an error that the `default thread already exists`

**Comment by sanderpick** [comment]
Probably related to adding a thread when node is offline... we'll need to chat about this

**Comment by asutula** [comment]
So, we should wait to create threads until the node is 'online'... Looking at the code, it seems like that is after the `Start` method returns or after the `onOnline` event is fired (the event is fired asynchronously from the `Start` method). Which should we wait for?

If the answer is the `onOnline` event, I'm curious what types of conditions would cause that to fail/not fire and what the UX should be in that case.

**Comment by asutula** [comment]
Currently have a branch where the node is created, then started, but then we wait for `onOnline` before checking if the `default` thread exists, creating it if needed, and querying for photos. This seems to work.

**Comment by sanderpick** [comment]
K, cool. The new service layer further complicates things. We can def improve it though. In the meantime, I can at least let the mobile layer only delay fetching photos in the case where you need to create the default (the first launch)

**Comment by sanderpick** [comment]
should be able to get that in later tonight

**Comment by sanderpick** [comment]
I was confused on this, shouldn't need to be online to create a thread (I was thinking of devices). Trying to recreate the behavior you layout above by adding a thread when we're not yet online, then stopping the node (even tried destroying it), and then re-starting (or creating then starting)... seems the thread is still there when listing (even when it's not yet online). I might be missing a detail here, let's chat about this too!

**Comment by asutula** [comment]
Previously, we were creating the threads after the node was created, before it was started. Maybe the issue is that it needs to be after it is started? Its more of a non-issue now because thread querying/creation is happening on demand.

General question... What _does_ change once the node is online?

**Comment by sanderpick** [comment]
That makes sense. So, previously, creating a thread was just a matter of writing to the sqllite instance, which auto-opens if not already open. Now, it does that but then we "load" the thread, which requires an instance of the ipfs node, which is created until you call start on the textile node.

**Comment by sanderpick** [comment]
"Online" means the underlying ipfs node is bootstapped, chatting with at least one other peer. You can't do any of the service layer stuff (send updates to thread peers for example), without being connected to at least one other peer, otherwise any writes to the dht will be lost (in practice ipfs just throws as error)

**Comment by asutula** [comment]
Sounds good. Closing this issue then.
