### ISSUE TITLE
removeThread is by Name in Go

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-go#166]
You can see it in the bridge 

https://github.com/textileio/textile-mobile/blob/master/ios/NativeModules/TextileNode.m#L315

and saga

https://github.com/textileio/textile-mobile/blob/master/App/Sagas/TextileSagas.ts#L360

but in go

https://github.com/textileio/textile-go/blob/master/mobile/mobile.go#L257

**Comment by andrewxhill** [comment]
did you want to bang this one into https://github.com/textileio/textile-go/pull/158/files

**Comment by sanderpick** [comment]
it's in there!

**Comment by sanderpick** [comment]
everything that was by thread name, is now by id, same for devices.
