### ISSUE TITLE
New photo resizing

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-go#170]
I'm not sure what the specific sizes are yet, but opening the ticket with some todos here,

- [ ] Thumbnail: big enough to represent a thumbnail in any UI (desktop, ipad, etc)
- [ ] Large image: big enough to be the full screen, full res image in any UI
- [ ] Original: unchanged

We can then optimize it over the network, grab thumbs always, grab Large at view time and sub-sample any other intermediate sizes we might want. Then just grab the original size in cases by request (e.g. backup sync on desktop)

**Comment by sanderpick** [comment]
Diving into this... references: 

- Flickr: https://www.flickr.com/photos/timpeake/26721236693/sizes (of note, like the web version default is the 1024 large)
- Instagram: 640, 1080 (guessing something smaller for mobile squares)

Proposed mapping to our DAG structure, avoiding migrations:

- `/photo` - 1080 width (the "full" size, IG full, ~Flickr large)
- `/medium` - 640 width (for not-retina phones, IG normal, Flicker medium)
- `/small` - 320 width (~our current `/thumb` size, Flicker small)
- `/thumb` - 100 width (Flicker thumbnail)

A dedicated backup service would add the raw photo and maybe a larger size, like Flicker large 2048, or maybe our full, doubled, so 2160.

We could certainly do dynamic sizes as well. However, this doesn't seem to be a trend, at least in the social space. The addition of the two sizes above and the down-sampled full "`/photo`" gets us pretty far. Would definitely want to put an nginx reverse proxy for caching in front of cafe nodes if we're gonna do anything dynamic for any amount of real users.

**Comment by sanderpick** [comment]
Bumping these sizes some after powwow: 100t, 320s, 800m, 1600l
