### ISSUE TITLE
Create a new table of Contact List

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-go#178]
Aggregate all peer ids and meta into a single table and expose through a mobile method like, getContacts or similar

**Comment by sanderpick** [comment]
Adding this to the recovery project as it's needed for username discovery.

**Comment by sanderpick** [comment]
done in https://github.com/textileio/textile-go/pull/300/commits/8cdff15b62cfe81d2caea02a2ab3b081894e9229
