### ISSUE TITLE
Login is case sensitive 

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-go#192]

**Comment by sanderpick** [comment]
could we just make the login textbox lowercase only?

**Comment by asutula** [comment]
Not sure it's possible to force only lowercase input, short of post-processing the input. That is an option.

**Comment by sanderpick** [comment]
Might be a pain depending on how it's implimented, but was thinking just use the `text-transform: lowercase` css property. Can def just force to lower on the go side too... easy

**Comment by asutula** [comment]
Just feels weird to the user to type in an upper case and see it appear as lower case in the UI. They will think it's a bug. Better to just `.toLower()` it behind the scenes, in JS or Go.

**Comment by asutula** [comment]
To clarify, the UI will show whatever the user types.

**Comment by sanderpick** [comment]
cool, will add to my current go branch
