### ISSUE TITLE
SignUp method signature

### ISSUE THREAD

**Issue by asutula** [textileio/textile-go#196]
It's pretty confusing, at least what's generated in the .framework:

```
signUpWithEmail(username, password, email, referral)
```

Would be better as:
```
signUp(username, password, email, referral)
```

**Comment by sanderpick** [comment]
It's like that because it could be signUpWithPhone, signUpWithSomeDistributedId... the mobile frameworks wraps the core method which takes a registration object: https://github.com/textileio/textile-go/blob/master/mobile/mobile.go#L172

**Comment by asutula** [comment]
Ok, then it would be good to move email to be the first param

**Comment by asutula** [comment]
jives better with obj c and JS that way

**Comment by sanderpick** [comment]
cool, coming in cafe PR
