### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [textileio/textile-go#247]
Good day Sir I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before i begin my design. Hoping for your positive feedback. Thanks

**Comment by sanderpick** [comment]
Hi @mansya... thanks for the generous offer! We actually do have a logo: https://www.textile.photos/

**Comment by mansya** [comment]
This is a logo project textile ?
![20180821_102502](https://user-images.githubusercontent.com/33461607/44378713-2d121200-a4f2-11e8-86d1-54c5c9318f8f.png)

**Comment by sanderpick** [comment]
It is!

**Comment by mansya** [comment]
the logo is very good. Do you want to see a new design about this project?

**Comment by mansya** [comment]
if you think it's good. but I admit your logo is currently very good. :smiley:

**Comment by carsonfarmer** [comment]
I think we're pretty happy with the current logo @mansya 😄

**Comment by mansya** [comment]
haha. thank you for your contribution sir.
