### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference for desktop application

### ISSUE THREAD

**Issue by mlu-sfbayarea** [textileio/textile-go#301]
Hi there, try to run textileio desktop and get below error, any help? thanks in advance.

DB-MBP-MCG8WL:desktop mlu$ go run *.go -v
DEBU[0000] Running app built at
DEBU[0000] Resources folder doesn't exist, restoring resources...
DEBU[0000] Removing /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/resources
DEBU[0000] Restoring resources in /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/resources
DEBU[0000] Starting...
DEBU[0000] Provisioning...
DEBU[0000] Provisioning Astilectron...
DEBU[0000] Removing directory /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/astilectron
DEBU[0000] Disembedding vendor_astilectron_bundler/astilectron.zip into /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/astilectron-v0.27.0.zip...
DEBU[0000] Creating /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor
DEBU[0000] Creating /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/astilectron-v0.27.0.zip
DEBU[0000] Disembedding vendor_astilectron_bundler/astilectron.zip
DEBU[0000] Copying disembedded data to /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/astilectron-v0.27.0.zip
DEBU[0000] Creating directory /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/astilectron
DEBU[0000] Unzipping /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/astilectron-v0.27.0.zip/astilectron-0.27.0 into /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/astilectron
DEBU[0000] Provisioning Electron...
DEBU[0000] Removing directory /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64
DEBU[0000] Disembedding vendor_astilectron_bundler/electron.zip into /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64-v1.8.1.zip...
DEBU[0000] Creating /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor
DEBU[0000] Creating /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64-v1.8.1.zip
DEBU[0000] Disembedding vendor_astilectron_bundler/electron.zip
DEBU[0000] Copying disembedded data to /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64-v1.8.1.zip
DEBU[0000] Creating directory /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64
DEBU[0000] Unzipping /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64-v1.8.1.zip into /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64
DEBU[0002] Finishing provisioning electron for darwin system
DEBU[0002] Copying /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/resources/icon.icns to /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Electron.app/Contents/Resources/electron.icns
DEBU[0002] Replacing in /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Electron.app/Contents/Info.plist
DEBU[0002] Replacing in /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Electron.app/Contents/Frameworks/Electron Helper EH.app/Contents/Info.plist
DEBU[0002] Replacing in /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Electron.app/Contents/Frameworks/Electron Helper NP.app/Contents/Info.plist
DEBU[0002] Replacing in /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/Info.plist
DEBU[0002] Renaming /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Electron.app into /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Textile.app
DEBU[0002] Renaming /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Textile.app/Contents/MacOS/Electron into /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Textile.app/Contents/MacOS/Textile
DEBU[0002] Renaming /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Textile.app/Contents/Frameworks/Electron Helper EH.app into /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Textile.app/Contents/Frameworks/Textile Helper EH.app
DEBU[0002] Renaming /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Textile.app/Contents/Frameworks/Textile Helper EH.app/Contents/MacOS/Electron Helper EH into /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Textile.app/Contents/Frameworks/Textile Helper EH.app/Contents/MacOS/Textile Helper EH
DEBU[0002] Renaming /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Textile.app/Contents/Frameworks/Electron Helper NP.app into /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Textile.app/Contents/Frameworks/Textile Helper NP.app
DEBU[0002] Renaming /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Textile.app/Contents/Frameworks/Textile Helper NP.app/Contents/MacOS/Electron Helper NP into /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Textile.app/Contents/Frameworks/Textile Helper NP.app/Contents/MacOS/Textile Helper NP
DEBU[0002] Renaming /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Textile.app/Contents/Frameworks/Electron Helper.app into /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Textile.app/Contents/Frameworks/Textile Helper.app
DEBU[0002] Renaming /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Textile.app/Contents/Frameworks/Textile Helper.app/Contents/MacOS/Electron Helper into /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Textile.app/Contents/Frameworks/Textile Helper.app/Contents/MacOS/Textile Helper
DEBU[0002] Listening...
DEBU[0002] Executing...
DEBU[0002] Starting cmd /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/electron-darwin-amd64/Textile.app/Contents/MacOS/Textile /var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/vendor/astilectron/main.js 127.0.0.1:50164
DEBU[0002] Astilectron says: {"name":"app.event.ready","targetID":"app","displays":{"all":[{"id":69733248,"bounds":{"x":0,"y":0,"width":1440,"height":900},"workArea":{"x":0,"y":23,"width":1440,"height":822},"size":{"width":1440,"height":900},"workAreaSize":{"width":1440,"height":822},"scaleFactor":2,"rotation":0,"touchSupport":"unknown"},{"id":441019671,"bounds":{"x":-504,"y":-1440,"width":2560,"height":1440},"workArea":{"x":-504,"y":-1417,"width":2560,"height":1417},"size":{"width":2560,"height":1440},"workAreaSize":{"width":2560,"height":1417},"scaleFactor":1,"rotation":0,"touchSupport":"unknown"}],"primary":{"id":69733248,"bounds":{"x":0,"y":0,"width":1440,"height":900},"workArea":{"x":0,"y":23,"width":1440,"height":822},"size":{"width":1440,"height":900},"workAreaSize":{"width":1440,"height":822},"scaleFactor":2,"rotation":0,"touchSupport":"unknown"}},"supported":{"notification":true}}
DEBU[0002] Sending to Astilectron: {"name":"window.cmd.create","targetID":"1","sessionId":"2","url":"file:///var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/resources/app/index.html","windowOptions":{"backgroundColor":"#ffffff","center":true,"height":384,"icon":"/var/folders/j5/d5jntp9s0358y3ffh3nxx_t04nmp6q/T/go-build070166248/b001/exe/resources/icon.png","show":false,"title":"Textile","titleBarStyle":"hidden-inset","width":384}}
DEBU[0002] Stderr says: 2018-10-04 13:54:52.683 Textile[64178:2533576] *** WARNING: Textured window <AtomNSWindow: 0x7fb3f2f4c110> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
DEBU[0002] Astilectron says: {"name":"window.event.ready.to.show","targetID":"1"}
DEBU[0002] Astilectron says: {"name":"window.event.did.finish.load","targetID":"1"}
DEBU[0002] Sending to Astilectron: {"name":"window.cmd.show","targetID":"1"}
DEBU[0002] Astilectron says: {"name":"window.event.focus","targetID":"1"}
DEBU[0002] Astilectron says: {"name":"window.event.show","targetID":"1"}
Successfully raised file descriptor limit to 2048.
DEBU[0005] Closing...
ERRO[0005] accept tcp 127.0.0.1:50164: use of closed network connection while TCP accepting
ERRO[0005] read tcp 127.0.0.1:50164->127.0.0.1:50165: use of closed network connection while reading
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4aac308]

goroutine 1 [running]:
textile-go-master/vendor/github.com/textileio/textile-go/gateway.(*Gateway).Start(0x0, 0xc00245e190, 0xf)
/Users/mlu/go/src/textile-go-master/vendor/github.com/textileio/textile-go/gateway/main.go:36 +0x288
main.start(0xc0002cc6c0, 0xc0001d6818, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
/Users/mlu/go/src/textile-go-master/desktop/main.go:196 +0x492
textile-go-master/vendor/github.com/asticode/go-astilectron-bootstrap.Run(0x0, 0x5153fa0, 0x5153f98, 0x0, 0x4fd306a, 0x7, 0x4fe47b5, 0x13, 0x4fe3021, 0x12, ...)
/Users/mlu/go/src/textile-go-master/vendor/github.com/asticode/go-astilectron-bootstrap/run.go:172 +0x7af
main.bootstrapApp()
/Users/mlu/go/src/textile-go-master/desktop/bootstrap.go:13 +0x34d
main.main()
/Users/mlu/go/src/textile-go-master/desktop/main.go:50 +0x2a
exit status 2

**Comment by sanderpick** [comment]
Closing this because we're ditching the desktop UI for a simple dropbox-like sync tool.
