### ISSUE TITLE
Desktop on Windows sometimes stuck on splash screen

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-go#319]
Sometimes, upon firing up a Win desktop build, the app gets stuck on the Textile splash-screen (rather than showing a QR code for pairing). It seems to be linked to an event that's not firing on Windows?

This doesn't _seem_ to occur if the desktop has already paired (i.e., the repo has been populated), though this needs to be tested further.

**Comment by sanderpick** [comment]
killing this, desktop going bye bye
