### ISSUE TITLE
Consider switching to experimental IPFS filestore

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-go#325]
Requires all IPFS 'adds' to use `nocopy` arg to work. This feature is really only useful for local adds. Pinned data will still be added to the 'blocks' IPLD store as per usualy. But _local_ adds are left in place, and only references to the actual (photo) data are kept in the filestore. This _could_ provide a drastic reduction in storage space when lots of photos are added locally. Requires serious testing on mobile to ensure it works.
Downside would be that, references to data added locally that gets moved will stop working. So it would potentially require the app to track moved/deleted files, or some other solution.

**Comment by carsonfarmer** [comment]
For reference, to play with this on Desktop for testing, this is the setup I initially used:

```
export IPFS_PATH=~/.ipfs2
ipfs init --empty-repo
ipfs config --json Experimental.FilestoreEnabled true
ipfs config Addresses.API "/ip4/127.0.0.1/tcp/5002"
ipfs config Addresses.Gateway "/ip4/127.0.0.1/tcp/8081"
ipfs daemon
```
In separate shell
```
ipfs pin add /ipfs/QmaNPfoeDvQjxBuUw3bFukFBxK9oucSw68sMAofHeedfCH
ipfs add image1.jpeg
ipfs add --nocopy image2.jpeg
```

**Comment by sanderpick** [comment]
prob not a viable option, right?
