### ISSUE TITLE
Remove time component from for AES-GSM keys

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-go#326]
Thanks to a potential vulnerability pointed out in this thread: https://twitter.com/Textile01/status/1054773192382922753
We should just move to reading 44 bytes from crypto/rand Reader and be done with it. This gives us a cryptographically secure random number generator, even on mobile.

**Comment by sanderpick** [comment]
Ah yeah, duh... relic from lazily wanting a pre-utf8 compatible AES key. We can just base58 encode the random bytes when we need it as a string for URL parameters.

**Comment by sanderpick** [comment]
done in https://github.com/textileio/textile-go/pull/300/commits/386b63cbea9defa362d18013f1651d7a19514c34

**Comment by carsonfarmer** [comment]
Thanks for the quick turnaround on that one @sanderpick:
> With this change plus the thread encryption updates in 05a269cd5dd72da224c4d2c472abad00a078d4ca, we'd be ready for an actual security review.

For those following along at home, this fix should make it into release once #300 is done and merged.
