### ISSUE TITLE
Peer invite API, addPeer(byId)

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-go#342]
Similar to https://github.com/textileio/textile-go/issues/336 but in this case I don't want to actually add that peer to any thread, I just want them in my contacts

Example is, you want to invite a bunch of people to textile to share photos but not create a Thread for them all. In the future, this would be the entry to p2p direct share, but already useful.

Will allow me to create an 'Invite' button directly on your peer list

**Comment by sanderpick** [comment]
I can add this as `AddContact(id string, address string, username string) error`. These are updated via thead joins / announces, so we _could_ leave the address and username empty on a first time add.
