### ISSUE TITLE
Own files, commets, likes data with incorrect username

### ISSUE THREAD

**Issue by asutula** [textileio/textile-go#388]
The `username` property of `ThreadFilesInfo`, `ThreadCommentInfo`, and `ThreadLikesInfo` is coming back as the first part of the peer id for items that are your own. Other peer's data looks correct.

**Comment by sanderpick** [comment]
Hmm, darn. Makes sense though. This is cause those methods try to find the username in contacts, but of course you don't have yourself as a contact. doh

**Comment by carsonfarmer** [comment]
Could a peer just auto-add itself to its own contacts? Or will that mess things up?

**Comment by asutula** [comment]
fwiw... icould contacts has the concept of a "self" contact, kinda helpful sometimes
