### ISSUE TITLE
Recursive message cli cmd calls list files after initial 'limit' is reached

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-go#479]
**Describe the bug**
The `callLsMessages` function has a recursive call in it to fetch more messages after `limit` has been reached. Currently, rather than recursively calling itself, it calls to `callLs`, which is the function to fetch thread files. This is a simple typo.

**To Reproduce**
1. `textile messages ls -l 1
2. Hit return

**Expected behavior**
Should continue to list messages, rather than files/error.

**Desktop (please complete the following information):**
 - OS: OSx
 - Textile Version 1.0.0-rc27

**Proposed fix**
Just fix typo and all will be well.

**Comment by sanderpick** [comment]
oh! good eye
