### ISSUE TITLE
Simpler APIs (REST and Go) on 'desktop' for milling and adding data to a thread

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-go#551]
**Is your feature request related to a problem? Please describe.**
Currently, adding data to a thread via the cli or react-native apis is pretty straightforward from an end-user, developer standpoint. This is because those 'clients' wrap much of the milling, adding, etc process in simple APIs. For example, there is a lot going on in backgorund of the [`textile files add`](https://github.com/textileio/textile-go/blob/master/cmd/files.go#L112) cli tool. Unfortunately, this makes it quite hard for 'newcomers' trying to build new clients via the REST API or similar.

**Describe the solution you'd like**
Ideally, we'd have an (alternative) simpler REST API endpoint and set of client APIs that area a bit easier to use for an outside developer. We might even consider creating a higher-level go API that looks a lot more like the mobile API, similarly exposing this API via REST and a Textile object with mobile-like methods?

**Describe alternatives you've considered**
Leaving the milling and schema efforts to the client libs works well when we are the ones writing the client libs, but it presents a large barrier to entry for external devs. This might be a good way to simplify things.

**Additional context**
This issue has cropped up in two contexts, 1) when trying to get folks at EthDenver to consider building on Textile on desktop or via browser, and 2) when discussing JS implementations and usage of Textile in other contexts.

**Comment by sanderpick** [comment]
I see the pain here for sure... but the REST API shouldn't need to be "simple", that's what clients are for. I'm not sure how schema fulfillment count be simplified - it's a complex task. I think we just need to provide a good JS client that folks can use / contribute to.

**Comment by carsonfarmer** [comment]
That's a valid argument 😄  What about allowing multipart-form data to be directly added to an existing thread with an existing schema like on desktop? Is this making too many strong assumptions? Could we not assume the existing schema should be fulfilled if possible?

Having posed these questions, totally agree a nice clear JS client would be ideal here. Just trying to think through making it easier to add new clients in general (e.g., Py, JS, bash, etc).

**Comment by sanderpick** [comment]
You could, but the files in the multipart request need to be generated by the mill APIs. So, then you're just sending data back and forth... which is why the input to add files is just a set of file index objects. If you instead took each file in the multipart request as pre-milled input for each step, then you're back to blowing out the server.

Compared to something like https://github.com/mongodb/node-mongodb-native, a textile-js client would be pretty simple.

**Comment by carsonfarmer** [comment]
Ah yes, this explanation makes sense, thanks for the clarification.
The IPFS http-client lib is another pretty nice example (we've used it in our own posts and textile build): https://github.com/ipfs/js-ipfs-http-client. Though this is more of a wrapper than a true 'client', in the sense that it is mostly a 1-to-1 API. Either way, would be great to add JS Client coordination to an upcoming sprint 👍

**Comment by sanderpick** [comment]
Agreed! Sounds like a lot of people want it. Just to further clarify... this might be misleading: "files in the multipart request would need to be generated by the mill APIs" - in some cases the bytes are just passed though (blob mill), but the index object still needs to be created... I suppose those can be considered the true output / result of milling.

**Comment by carsonfarmer** [comment]
Closing (wontfix) in favor of a client-based approach.
