### ISSUE TITLE
searchContacts never resolves in some cases

### ISSUE THREAD

**Issue by asutula** [textileio/textile-go#554]
The pattern I'm seeing:

If the search returns no results, the promise resolves after `wait` amount of seconds.

If the search does send a result to the `handler`, the promise never resolves.

**Comment by andrewxhill** [comment]
just moving this issue over here so we can investigate further. confirmed that I see the same behavior at the bridge level. specifically here, 

https://github.com/textileio/react-native-sdk/blob/master/ios/TextileNode.m#L332

I see a DONE result come back if we hit the time limit without finding any result.

If we find a result before reaching the time limit, no DONE event will happen. 

One quick fix. There is a bunch of cleanup to do around this handling anyway, so one simple solution would be to just handle the timeout event right in the SDK. we already know when it should happen, so as long as we don't get an early DONE we can fire it off.

**Comment by sanderpick** [comment]
Crap, not surprising I guess... no test for this guy. I'm sure it's simple ™, can look once tonight/morning...
