### ISSUE TITLE
Single-use encryption key for every photo / file

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-go#84]
Flagging this here, @andrewxhill mentioned a protocol he came across that creates a keypair for each file and thought it could possibly solve some issues for us... what was is called?

**Comment by andrewxhill** [comment]
so the primary one is DAT, where they use the link to the file as the password itself

**Comment by sanderpick** [comment]
Dug into DAT pretty far, super cool project! There's a bunch of these: https://livingthing.danmackinlay.name/synchronising_files.html

Of course, since we're IPFS based, our file links are predetermined. We could definitely construct _our own_ links / protocol layer for easy sharing like DAT... which seems like a killer idea

**Comment by sanderpick** [comment]
renamed this issue to reflect the work, also gave a v2 label so we can group these tasks under a common design goal.
